// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBghW4bB7e8F_GdExwus_laMseTefaWm8',
    appId: '1:1031670707590:web:fe83c38fd77bdb9c17e807',
    messagingSenderId: '1031670707590',
    projectId: 'ecommerceapp-9b2f5',
    authDomain: 'ecommerceapp-9b2f5.firebaseapp.com',
    storageBucket: 'ecommerceapp-9b2f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdb1uyjIv2FG64f2OebezE5buHv648TQ8',
    appId: '1:1031670707590:android:9c94d96d2f2447ab17e807',
    messagingSenderId: '1031670707590',
    projectId: 'ecommerceapp-9b2f5',
    storageBucket: 'ecommerceapp-9b2f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_x8P8wOVgaWwdQHGdy2Thh5AD2XNrpN4',
    appId: '1:1031670707590:ios:f520800a912fbfe017e807',
    messagingSenderId: '1031670707590',
    projectId: 'ecommerceapp-9b2f5',
    storageBucket: 'ecommerceapp-9b2f5.firebasestorage.app',
    androidClientId: '1031670707590-g4t8iuhfktu8okj1si89nsrvus35pjs1.apps.googleusercontent.com',
    iosClientId: '1031670707590-dtvvqld9gah478mh2kl3gg5on6u255p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );

}