// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYlDIwXdVxGevaidHeWqJ2ibESr9h4Ff4',
    appId: '1:251852486318:web:540712c8c31a0bd231df3f',
    messagingSenderId: '251852486318',
    projectId: 'ecommerceapp-42b06',
    authDomain: 'ecommerceapp-42b06.firebaseapp.com',
    storageBucket: 'ecommerceapp-42b06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_Eaca7O5eZttKYLztasyZ9QyhjjCPVE',
    appId: '1:251852486318:android:22a92b79b886e5a031df3f',
    messagingSenderId: '251852486318',
    projectId: 'ecommerceapp-42b06',
    storageBucket: 'ecommerceapp-42b06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf6mvajSvuKNlDPGZ9Ey7X3K_pswHHrRM',
    appId: '1:251852486318:ios:17793e08d602c23231df3f',
    messagingSenderId: '251852486318',
    projectId: 'ecommerceapp-42b06',
    storageBucket: 'ecommerceapp-42b06.firebasestorage.app',
    androidClientId: '251852486318-csp3t94ueg9il1fumhgv51vsio5u24in.apps.googleusercontent.com',
    iosClientId: '251852486318-dqeob1pq5b6b413g9clq0479mm1k0aoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
